import prisma from "@/db";
import { buildSynthesisText, checkEligibility } from "./extractText";
import { getTtsProvider } from "./providers";
import { storeAudio } from "./storage";
import { checkRateLimit, recordRateLimit } from "./rateLimit";
import type { TtsGenerateResult } from "./types";

export type GenerateForPostResult =
    | { ok: true; audioUrl: string; provider: string; durationMs: number; cached: boolean }
    | { ok: false; code: string; message: string; status: number };

/**
 * Core TTS orchestration — validates eligibility, rate limits, provider
 * availability, synthesizes, persists, and updates Post.audio* fields.
 *
 * Never mutates publishing state.
 */
export async function generateAudioForPost(args: {
    postId: string;
    userId: string;
    force?: boolean;
}): Promise<GenerateForPostResult> {
    const post = await prisma.post.findUnique({
        where: { id: args.postId },
        select: {
            id: true,
            title: true,
            description: true,
            content: true,
            published: true,
            userId: true,
            audioUrl: true,
            audioStatus: true,
        },
    });

    if (!post) return { ok: false, code: "NOT_FOUND", message: "Post not found.", status: 404 };

    // Access: published posts are readable by any authenticated user; drafts only by owner.
    if (!post.published && post.userId !== args.userId) {
        return { ok: false, code: "FORBIDDEN", message: "Draft audio can only be generated by the author.", status: 403 };
    }

    const text = buildSynthesisText({
        title: post.title,
        description: post.description,
        content: post.content,
    });

    const eligibility = checkEligibility(text);
    if (!eligibility.eligible) {
        await prisma.post.update({
            where: { id: post.id },
            data: { audioStatus: "failed", audioError: eligibility.reason },
        }).catch(() => {});
        return {
            ok: false,
            code: eligibility.code ?? "UNSUPPORTED_CONTENT",
            message: eligibility.reason ?? "Content not eligible for audio.",
            status: 400,
        };
    }

    // If already ready and not forced, return cached URL (no rate-limit hit).
    if (!args.force && post.audioUrl && post.audioStatus === "ready") {
        return { ok: true, audioUrl: post.audioUrl, provider: "cached", durationMs: 0, cached: true };
    }

    const rate = checkRateLimit({ userId: args.userId, postId: post.id });
    if (!rate.allowed) {
        return {
            ok: false,
            code: "RATE_LIMITED",
            message: `Rate limited. Try again in ${Math.ceil((rate.retryAfterMs ?? 60000) / 1000)}s.`,
            status: 429,
        };
    }

    const provider = getTtsProvider();
    // Strict VoxCPM path: if VOXCPM was explicitly requested but not available, surface UNAVAILABLE
    if (provider.name === "voxcpm" && !provider.isAvailable()) {
        return {
            ok: false,
            code: "UNAVAILABLE",
            message:
                "VoxCPM service is not configured. Set VOXCPM_API_URL or use TTS_PROVIDER=mock for the built-in placeholder synthesizer.",
            status: 503,
        };
    }

    // Mark generating — non-blocking for readers; failures are surfaced on next GET/POST.
    await prisma.post.update({
        where: { id: post.id },
        data: { audioStatus: "generating", audioError: null },
    }).catch(() => {});

    let result: TtsGenerateResult;
    try {
        result = await provider.synthesize({ text, postId: post.id });
    } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        const isAbort = msg.toLowerCase().includes("abort");
        await prisma.post.update({
            where: { id: post.id },
            data: { audioStatus: "failed", audioError: msg.slice(0, 1000) },
        }).catch(() => {});
        return {
            ok: false,
            code: isAbort ? "TIMEOUT" : "GENERATION_FAILED",
            message: `Audio generation failed: ${msg}`,
            status: 502,
        };
    }

    // Persist bytes
    let audioUrl: string;
    try {
        audioUrl = await storeAudio({ postId: post.id, buffer: result.audioBuffer, ext: result.ext });
    } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        await prisma.post.update({
            where: { id: post.id },
            data: { audioStatus: "failed", audioError: `Storage failed: ${msg}` },
        }).catch(() => {});
        return { ok: false, code: "STORAGE_FAILED", message: `Failed to store audio: ${msg}`, status: 500 };
    }

    // Estimate duration if provider didn't return it (mock always does)
    let durationMs = result.durationMs;
    if (!durationMs || durationMs === 0) {
        // Derive from file size for WAV: bytes per ms ≈ byteRate/1000
        durationMs = Math.round(result.audioBuffer.length / 48); // rough 24kHz*2 bytes ~48 bytes/ms
    }

    await prisma.post.update({
        where: { id: post.id },
        data: {
            audioUrl,
            audioStatus: "ready",
            audioProvider: result.provider,
            audioGeneratedAt: new Date(),
            audioDurationMs: durationMs,
            audioError: null,
        },
    });

    recordRateLimit({ userId: args.userId, postId: post.id });

    return { ok: true, audioUrl, provider: result.provider, durationMs, cached: false };
}

export async function getAudioStatus(postId: string) {
    const post = await prisma.post.findUnique({
        where: { id: postId },
        select: {
            id: true,
            audioUrl: true,
            audioStatus: true,
            audioProvider: true,
            audioGeneratedAt: true,
            audioDurationMs: true,
            audioError: true,
        },
    });
    if (!post) return null;
    return post;
}
